events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        # 1. Đường vào User Service (Lấy Token)
        location /api/users/ {
            # Rewrite bỏ đi chữ /api/users/ để khớp với URL gốc của User Service
            rewrite ^/api/users/(.*) /$1 break;
            proxy_pass http://user-service:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 2. Đường vào Kho Hàng (Product)
        location /api/products/ {
            rewrite ^/api/products/(.*) /products/$1 break;
            proxy_pass http://product-service:8000;
        }

        # 3. Đường vào Giỏ Hàng (Cart)
        location /api/cart/ {
            # Cart Service bản thân nó đã có tiền tố /api/cart/ nên không cần rewrite
            proxy_pass http://cart-service:8000;
        }

        # 4. Đường vào Chốt Đơn (Order)
        location /api/orders/ {
            proxy_pass http://order-service:8000;
        }
    }
}