# Generated by Django 5.2.12 on 2026-03-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('method', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('status', models.CharField(default='Preparing', max_length=50)),
            ],
        ),
    ]
